[package]
name = "rscpi"
description = "Rust library for USBTMC"
homepage = "https://github.com/danchitnis/rscpi"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
futures-lite = "2.2.0"
nusb = "0.1.7"
